### ISSUE TITLE
UiDemoTvm doesn't run 

### ISSUE THREAD

**Issue by SergeyKhokhryakov** [m-m-m/ui-demo#2]
### Steps to reproduce

1. Run UiDemoTvm.main() 

### Actual behavior
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Exception in thread "main" java.util.ServiceConfigurationError: io.github.mmm.ui.api.controller.UiNavigationManager: io.github.mmm.ui.tvm.controller.TvmNavigationManager Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.github.mmm.base.service.ServiceHelper.singleton(ServiceHelper.java:51)
	at io.github.mmm.base.service.ServiceHelper.singleton(ServiceHelper.java:37)
	at io.github.mmm.ui.impl.controller.UiNavigationManagerProvider.<clinit>(UiNavigationManagerProvider.java:19)
	at io.github.mmm.ui.api.controller.UiNavigationManager.get(UiNavigationManager.java:101)
	at io.github.mmm.ui.demo.tvm.UiDemoTvm.start(UiDemoTvm.java:15)
	at io.github.mmm.ui.demo.tvm.UiDemoTvm.main(UiDemoTvm.java:23)
Caused by: java.lang.NoClassDefFoundError: org/teavm/jso/JSObject
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getConstructor(Class.java:2442)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.teavm.jso.JSObject
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 18 more

Process finished with exit code 1

**Comment by hohwille** [comment]
@SergeyKhokhryakov thanks for reporting this bug and sorry for the delayed response.
TeaVM is compiling JavaCode to JavaScript or WebAssembly what is quite a challenging task.
At the moment this project is still in a somewhat early phase where I sometimes change and refactor things.
Typically with my CI processes and all that I did setup, I quickly notice when things break.
It seems here I have to improve!
Typically these types of errors from the TeaVM compiler arise when I use new special Java features not (yet) covered by TeaVM.
I therefore already contributed some PRs to TeaVM project itself to make it work.
However, this error that you reported looks a little different and maybe is a new bug in TeaVM itself so I have to check for updates and investigate further. Unfortunately I am a little busy at the moment so I might need several weeks to get this resolved. Sorry for any inconvenience and thanks for trying mmm. I hope you at least managed to run the JavaFx part of the demo. For android there are even things missing in the implementation and some tricky problems are yet to be solved. iOS is not yet even on the list and therefore I would really need quite some manpower joining the community of this project.

**Comment by hohwille** [comment]
Ah, and if you just want to try it out, you could go back to maybe [this commit](https://github.com/m-m-m/ui-demo/commit/0d6560e11229f28a65243e635d295663c07a7bd0#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8) and change the revision from `0-SNAPSHOT` to an older release like e.g. `0.9.1`
https://repo1.maven.org/maven2/io/github/m-m-m/mmm-base/

**Comment by hohwille** [comment]
I updated teavm.version to `0.10.0` but now I am facing this error:
https://github.com/konsoletyper/teavm/issues/918
Sorry, it seems we are still blocked with getting `ui-demo` running in the browser again.

**Comment by hohwille** [comment]
fixed. Sorry for the long delay. I was sick for quite a long time...
